services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mydatabase:/var/lib/mysql

    
    mem_limit: 256m # limiting the ram usage
    cpus: 0.5 #limit to half of a CPU core
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  myportfolio:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=affiqem@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./certbot/www:/var/www/certbot
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
