version: '3.8'
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mydatabase:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  myportfolio:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mydatabase: